### PR TITLE
feat(MapPtr): returns a map with pointers to the struct fields

### PR DESCRIPTION
**Pull request by themihai**

### CODE REVIEW

**Comment by fatih** [comment]
Hi @themihai 

Thanks for the contribution. Can you please give more information what it's doing and for what you need it? I'm trying to understand the addition.

Also can you rebase your changes to the latest master. Coverall API has change and it should not fail now.

**Comment by themihai** [comment]
It returns a map with pointers to the struct fields.
1.  You may need this if the struct field values are big (the pointers are more efficient)
2. This is the actual reason of the PR: The pointers help you keep the values of the map and the original struct in sync.  You can use the map as a structure to marshal/unmarshal a single payload (e.g. json) into multiple structs(e.g. convert struct1 to map, convert the 2nd struct to map and merge it into one and then unmarhal the payload into the super map). You can do this with the current Map too but if you have methods on the structs you can't use them because the data is stored on the map not on the structs. With MapPtr the data is stored in the original struct as the map values are actually pointers to the struct fields so after you unmarshal it you can use the methods and even delete/garbage collect the map.
 Let me know if it makes sense and if the feature is accepted so that I can rebase and send another PR.

**Comment by kamronbatman** [comment]
@themihai I needed this change too, so I remerged your code into my fork and submitted.

**Comment by fatih** [comment]
Closing this as well as the PR is not ready and there is not much value using it. I'm open for another PR with coverage being the same and some use cases that makes sense to introduce such a change.

**Pull request closed without merging**
