### PR TITLE
Anonymous fields now get merged into the map

### PR DESCRIPTION
**Pull request by jraede**
Currently anonymous fields get set as a property on the converted map. However, since they're anonymous they should really be merged into the map instead. This checks if the field is anonymous when recursively running `Map()` and merges the result into `out` if `Anonymous` is `true`.

Additionally, the `Struct` type has support for a custom tag name (other than "structs"), but this is not carried down recursively into nested maps. I changed the logic so instead of just running `Map()`, I create a new instance of `Struct`, set the tag name, and use the result of `struct.Map()` instead of `Map()`

### CODE REVIEW

**Comment by fatih** [comment]
Hi @jraede thanks for the contribution and PR.

This is a tricky case, because once you try to merge it, you might override an existing value, or an existing value might override your merged values. This is mainly due how you place the field with the same name in the outer struct. Here is an example that fails for example:

```go
func TestMap_AnonymousDuplicate(t *testing.T) {
	type A struct {
		Name string
	}
	a := &A{Name: "example"}

	type B struct {
		*A
		Name string
	}
	b := &B{Name: "example2"}
	b.A = a

	m := Map(b)

	if typ := reflect.TypeOf(m).Kind(); typ != reflect.Map {
		t.Errorf("Map should return a map type, got: %v", typ)
	}

	_, ok := m["A"].(map[string]interface{})
	if ok {
		t.Error("Embedded structs should not be a property in the map")
	}

	if name := m["Name"].(string); name != "example" {
		t.Errorf("Embedded A struct's Name field should give example, got: %s", name)
	}
}
```

Bonus:

http://play.golang.org/p/ae3T6SAXrf

As you see, even if it's embedded, embedded fields correct values are accessed as they are separate field. This is a breaking change. As seen in the examples above. What we could do is, provide a tag option which explicitly let us merges the struct. So the responsibility of loosing values (overriding) would be on their users own terms.  Example:

```go
type B struct {
	*A `structs:",merge"`
}
```

This is just an example, but you get the idea. This also should be applicable to all existing current methods too, such as `Values`, `Fields`, etc .. 

Are you ok with this idea? Let me know please. 

You second fix, carrying tag names are indeed something we should fix. Not only for Map, for all remaining methods which do recursive resolving, such as `Values`, `Fields`... I would like to tackle them in a separate PR instead of this.

**Comment by jraede** [comment]
That would work great. I think to fit in with other packages the keyword
should be "inline" rather than "merge", but either way it'll work fine.

Re: second fix, I can submit a PR for just that if it's easier. Let me
know.

Thanks

**Comment by fatih** [comment]
@jraede the `merge` keyword was just an example, `inline` is way better of course :) I just wanted to demonstrate what I had in my mind.

For the second fix, opening a PR would be better (if you want to do it). Also would be awesome if you include tests for all cases.

**Comment by jraede** [comment]
@fatih will do. Thanks

**Pull request closed without merging**
